# Generated by Django 2.0.2 on 2018-02-03 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('CF', 'Conferencia'), ('SM', 'Seminario'), ('CN', 'Congreso'), ('CR', 'Curso')], default='CF', max_length=2)),
                ('tipo_evento', models.CharField(choices=[('PR', 'Presencial'), ('VR', 'Virtual')], default='PR', max_length=2)),
            ],
        ),
    ]
